import os
import re

dir_path = "/home/johnny/Documents/PocketFlow-Tutorial-Codebase-Knowledge/output_tutorials/seos/"
index_file = os.path.join(dir_path, "index.md")

with open(index_file, "r") as f:
    index_content = f.read()

chapters_split = index_content.split("## Chapters")
header = chapters_split[0]

footer = "\n---\n\nGenerated by [AI Codebase Knowledge Builder]"
if "---" in chapters_split[1] and "Generated by" in chapters_split[1]:
    pass # we'll just ignore index's footer and append ours at the very end

files = [
    "01_基礎平台與共用服務_.md",
    "02_前端介面與_api_對接_.md",
    "03_參考資料與欄位對照平台_.md",
    "04_多語係與關鍵字字典管理_.md",
    # "05_單據參數建檔主資料_.md",
    # "06_假日與寬限設定管理_.md",
    # "07_通知名單與收件部門設定_.md",
    # "08_廠商與報到資料維護_.md",
    # "09_智慧立案與逾期效獎業務核心_.md",
    # "10_逾期效獎減發確認流程_.md"
]

merged_content = header.strip() + "\n\n"

for f_name in files:
    with open(os.path.join(dir_path, f_name), "r") as f:
        content = f.read()
        
        # Strip out the previous/next chapter links or footer if we want, but preserving most is fine
        content = re.sub(r'---[\n\s]*Generated by \[AI Codebase Knowledge Builder\].*', '', content)
        
        merged_content += "\n\n" + content.strip() + "\n\n"
        
merged_content += "\n--- \n\nGenerated by [AI Codebase Knowledge Builder](https://github.com/The-Pocket/Tutorial-Codebase-Knowledge)\n"

# get the current directory of this script 
current_dir = os.path.dirname(os.path.abspath(__file__))

out_file = os.path.join(current_dir, "partial_1to4_tutorial.md")
with open(out_file, "w") as f:
    f.write(merged_content)
print(f"Created {out_file}")
